# Generated by Django 3.0.3 on 2020-02-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_firstname', models.CharField(max_length=50)),
                ('employee_lastname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('cell_number', models.IntegerField()),
                ('dispatch_company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('date_started', models.DateField(blank=True)),
                ('picture', models.ImageField(upload_to='employee_img')),
            ],
        ),
    ]
