# Generated by Django 3.0.3 on 2020-02-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200224_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_lastname',
            new_name='lastname',
        ),
    ]
