# Generated by Django 3.0.3 on 2020-02-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200224_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='picture',
        ),
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='MALE', max_length=20),
        ),
    ]
