# Generated by Django 3.0.3 on 2020-02-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200229_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='MALE', max_length=20),
        ),
    ]
