# Generated by Django 3.0.3 on 2020-02-29 07:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200229_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='country',
            field=django_countries.fields.CountryField(default='Select Country', max_length=2),
        ),
    ]
