# Generated by Django 3.0.3 on 2020-02-29 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_started',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
